version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: ./services/auth/
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - ./services/auth/:/app
      - /app/node_modules
    environment:
      JWT_SECRET: ${JWT_SECRET}
