version: "3.2"
services:
  auth:
    build:
      context: ./services/auth/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./services/auth/:/app
      - /app/node_modules
    environment:
      JWT_SECRET: ${JWT_SECRET}

  movies:
    build:
      context: ./services/movies/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/movies/:/app
      - /app/node_modules
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
