version: "3.2"
services:
  movies:
    command: npm run test:${TEST}
    build:
      context: ./services/movies/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/movies/:/app
      - /app/node_modules
