name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: unit tests
        run: TEST=unit docker-compose -f docker-compose.ci.yml up

      - name: e2e tests
        run: TEST=e2e docker-compose -f docker-compose.ci.yml up
